CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE TABLE IF NOT EXISTS users(id text PRIMARY KEY,login text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS sessions(token_hash text PRIMARY KEY,user_id text NOT NULL REFERENCES users(id),expires_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS workspaces(id uuid PRIMARY KEY,owner_id text NOT NULL REFERENCES users(id),name text NOT NULL CHECK(length(name) BETWEEN 1 AND 80),created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS api_keys(id uuid PRIMARY KEY,user_id text NOT NULL REFERENCES users(id),workspace_id uuid NOT NULL REFERENCES workspaces(id),token_hash text NOT NULL UNIQUE,name text NOT NULL,scope text NOT NULL CHECK(scope IN ('read','source:write','publish')),created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS sources(id uuid PRIMARY KEY,workspace_id uuid NOT NULL REFERENCES workspaces(id),revision int NOT NULL DEFAULT 1 CHECK(revision=1),name text NOT NULL,kind text NOT NULL,origin text NOT NULL,content_hash text NOT NULL,payload_hash text NOT NULL,object_key text NOT NULL,line_count int NOT NULL,idempotency_key text NOT NULL,masked boolean NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),deleted_at timestamptz,UNIQUE(workspace_id,id),UNIQUE(workspace_id,idempotency_key));
CREATE TABLE IF NOT EXISTS publications(id uuid PRIMARY KEY,workspace_id uuid NOT NULL REFERENCES workspaces(id),idempotency_key text NOT NULL,payload_hash text NOT NULL,producer jsonb NOT NULL,reason text NOT NULL,result jsonb,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(workspace_id,id),UNIQUE(workspace_id,idempotency_key));
CREATE TABLE IF NOT EXISTS articles(id uuid PRIMARY KEY,workspace_id uuid NOT NULL REFERENCES workspaces(id),title text NOT NULL,content text NOT NULL,kind text NOT NULL CHECK(kind IN ('article','memory','glossary')),folder text NOT NULL DEFAULT '',tags text[] NOT NULL DEFAULT '{}',aliases text[] NOT NULL DEFAULT '{}',revision int NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),deleted_at timestamptz,UNIQUE(workspace_id,id));
CREATE TABLE IF NOT EXISTS revisions(workspace_id uuid NOT NULL,article_id uuid NOT NULL,revision int NOT NULL,title text NOT NULL,content text NOT NULL,metadata jsonb NOT NULL,publication_id uuid NOT NULL,reviewed_at timestamptz,reviewed_by text REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(workspace_id,article_id,revision),FOREIGN KEY(workspace_id,article_id) REFERENCES articles(workspace_id,id),FOREIGN KEY(workspace_id,publication_id) REFERENCES publications(workspace_id,id));
CREATE TABLE IF NOT EXISTS claims(workspace_id uuid NOT NULL,article_id uuid NOT NULL,revision int NOT NULL,anchor text NOT NULL,text text NOT NULL,type text NOT NULL CHECK(type IN ('user_decision','observation','ai_inference','unconfirmed','author_statement')),PRIMARY KEY(workspace_id,article_id,revision,anchor),FOREIGN KEY(workspace_id,article_id,revision) REFERENCES revisions(workspace_id,article_id,revision));
CREATE TABLE IF NOT EXISTS evidence(workspace_id uuid NOT NULL,article_id uuid NOT NULL,revision int NOT NULL,anchor text NOT NULL,source_id uuid NOT NULL,source_revision int NOT NULL CHECK(source_revision=1),line_start int NOT NULL,line_end int NOT NULL,quote text NOT NULL,PRIMARY KEY(workspace_id,article_id,revision,anchor,source_id,line_start,line_end),FOREIGN KEY(workspace_id,article_id,revision,anchor) REFERENCES claims(workspace_id,article_id,revision,anchor),FOREIGN KEY(workspace_id,source_id) REFERENCES sources(workspace_id,id));
CREATE TABLE IF NOT EXISTS links(workspace_id uuid NOT NULL,from_id uuid NOT NULL,to_id uuid NOT NULL,relation text NOT NULL CHECK(relation IN ('links_to','supersedes')),PRIMARY KEY(workspace_id,from_id,to_id,relation),FOREIGN KEY(workspace_id,from_id) REFERENCES articles(workspace_id,id),FOREIGN KEY(workspace_id,to_id) REFERENCES articles(workspace_id,id),CHECK(from_id<>to_id));
CREATE TABLE IF NOT EXISTS project_contexts(workspace_id uuid NOT NULL REFERENCES workspaces(id),tag text NOT NULL,article_id uuid NOT NULL,PRIMARY KEY(workspace_id,tag),FOREIGN KEY(workspace_id,article_id) REFERENCES articles(workspace_id,id));
CREATE INDEX IF NOT EXISTS article_title_trgm ON articles USING gin(title gin_trgm_ops) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS article_content_trgm ON articles USING gin(content gin_trgm_ops) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS article_workspace ON articles(workspace_id,updated_at DESC);
CREATE INDEX IF NOT EXISTS source_workspace ON sources(workspace_id,created_at DESC);
CREATE TABLE IF NOT EXISTS collection_streams(workspace_id uuid NOT NULL REFERENCES workspaces(id),id text NOT NULL,client text NOT NULL,session_id text NOT NULL,name text NOT NULL,last_position int NOT NULL DEFAULT -1,updated_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(workspace_id,id));
CREATE TABLE IF NOT EXISTS collection_events(workspace_id uuid NOT NULL,stream_id text NOT NULL,position int NOT NULL,content_hash text NOT NULL,source_id uuid NOT NULL,PRIMARY KEY(workspace_id,stream_id,position,content_hash),FOREIGN KEY(workspace_id,stream_id) REFERENCES collection_streams(workspace_id,id),FOREIGN KEY(workspace_id,source_id) REFERENCES sources(workspace_id,id));
CREATE TABLE IF NOT EXISTS ai_settings(workspace_id uuid PRIMARY KEY REFERENCES workspaces(id),config jsonb NOT NULL,encrypted_key text,version int NOT NULL DEFAULT 1,updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS refinement_jobs(id uuid PRIMARY KEY,workspace_id uuid NOT NULL,source_id uuid NOT NULL,status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','running','completed','failed')),attempts int NOT NULL DEFAULT 0,available_at timestamptz NOT NULL DEFAULT now(),lease_until timestamptz,run_id uuid,output jsonb,result jsonb,error_code text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(workspace_id,source_id),FOREIGN KEY(workspace_id,source_id) REFERENCES sources(workspace_id,id));
CREATE TABLE IF NOT EXISTS refinement_runs(id uuid PRIMARY KEY,workspace_id uuid NOT NULL,job_id uuid NOT NULL REFERENCES refinement_jobs(id),settings jsonb NOT NULL,prompt_version text NOT NULL,input jsonb NOT NULL DEFAULT '{}',output jsonb,usage jsonb,status text NOT NULL DEFAULT 'running',error_code text,created_at timestamptz NOT NULL DEFAULT now(),finished_at timestamptz);
ALTER TABLE refinement_runs ADD COLUMN IF NOT EXISTS output jsonb;
CREATE INDEX IF NOT EXISTS refinement_ready ON refinement_jobs(workspace_id,status,available_at);
CREATE INDEX IF NOT EXISTS refinement_daily ON refinement_runs(workspace_id,created_at);
ALTER TABLE workspaces ENABLE ROW LEVEL SECURITY;
ALTER TABLE workspaces FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS workspace_owner ON workspaces;
CREATE POLICY workspace_owner ON workspaces USING(owner_id=current_setting('app.user_id',true)) WITH CHECK(owner_id=current_setting('app.user_id',true));
DO $$ DECLARE t text; BEGIN
 FOREACH t IN ARRAY ARRAY['articles','revisions','sources','links','publications','claims','evidence','project_contexts','collection_streams','collection_events','ai_settings','refinement_jobs','refinement_runs'] LOOP
 EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',t);
 EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY',t);
 EXECUTE format('DROP POLICY IF EXISTS workspace_scope ON %I',t);
 EXECUTE format('CREATE POLICY workspace_scope ON %I USING (workspace_id::text=current_setting(''app.workspace_id'',true) AND EXISTS(SELECT 1 FROM workspaces w WHERE w.id=workspace_id)) WITH CHECK (workspace_id::text=current_setting(''app.workspace_id'',true) AND EXISTS(SELECT 1 FROM workspaces w WHERE w.id=workspace_id))',t);
 END LOOP;
END $$;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA public TO wiki_app;
GRANT USAGE ON SCHEMA public TO wiki_app;
GRANT CONNECT ON DATABASE agent_wiki TO wiki_app;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA public TO wiki_admin;
