local all all trust
hostssl agent_wiki wiki_admin 0.0.0.0/0 scram-sha-256
hostssl agent_wiki wiki_app 10.52.0.0/16 scram-sha-256
hostssl agent_wiki wiki_owner 10.52.0.0/16 scram-sha-256
host all all 0.0.0.0/0 reject
host all all ::/0 reject
